apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: win10
  namespace: vm-workloads
spec:
  osType: Windows
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 4G
  disks:
    - virtualMachineDiskName: win-boot-dv
      boot: true
  interfaces:
    - name: eth0
      networkName: pod-network
